// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sififzsmdnwftzxjxrra.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNpZmlmenNtZG53ZnR6eGp4cnJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwMzg2MDAsImV4cCI6MjA3MzYxNDYwMH0.CocwJC3YKH1zZhnfBiQ0rVVab6M62fwmVeHD7DDkQqc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});